version: "2"
services:
  seed:
    image: wordswithsalt:latest
    environment:
      CLUSTER_PORT: 7007
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed

  cluster-juan:
    image: wordswithsalt:latest
    environment:
      CLUSTER_IP: ""
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed